Traceback (most recent call last):
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np

x = np.linspace(-np.pi,np.pi,100)
h = x[1]-x[0]
xx = np.insert(x,[0,len(x)],[-np.pi-h, np.pi+h])
yy = list(map(lambda a: np.sin(a), xx)) + xx

fd = (yy[2:]-yy[:-2])/(2*h)

plt.plot(x, fd)
plt.xlabel('x')
plt.title('Estimated derivative of sin(x)+x')
plt.ylim(0,2)
plt.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m<ipython-input-1-973730cd837b>[0m in [0;36m<module>[1;34m[0m
[0;32m      8[0m [0mfd[0m [1;33m=[0m [1;33m([0m[0myy[0m[1;33m[[0m[1;36m2[0m[1;33m:[0m[1;33m][0m[1;33m-[0m[0myy[0m[1;33m[[0m[1;33m:[0m[1;33m-[0m[1;36m2[0m[1;33m][0m[1;33m)[0m[1;33m/[0m[1;33m([0m[1;36m2[0m[1;33m*[0m[0mh[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      9[0m [1;33m[0m[0m
[1;32m---> 10[1;33m [0mplt[0m[1;33m.[0m[0mplot[0m[1;33m([0m[0mx[0m[1;33m,[0m [0mfd[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     11[0m [0mplt[0m[1;33m.[0m[0mxlabel[0m[1;33m([0m[1;34m'x'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     12[0m [0mplt[0m[1;33m.[0m[0mtitle[0m[1;33m([0m[1;34m'Estimated derivative of sin(x)+x'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'plt' is not defined
NameError: name 'plt' is not defined

